config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  resources :users
  get 'home/index'

  resources :projects do
    resources :cards, except: [:show, :index] do
      collection { post :sort } 
    end
  end

  root 'home#index'
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :integer          not null, primary key
#  project_id :integer
#  title      :string(255)
#  body       :text
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Card < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :cards, -> {order("position ASC")}, dependent: :destroy
  validates_presence_of :title
  after_create :make_card

  def make_card
  	self.cards.create(title: "New Card", body: "This is your first card!", position: 1)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects 
  after_create :make_project

  def make_project
  	self.projects.create(title: "My First Project")
  end      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    # devise_parameter_sanitizer.for(:edit) << :name
  end

  def after_sign_in_path_for(resource)
  	project_path(resource.projects.last)
  end

  def after_sign_up_path_for(resource)
  	project_path(resource.projects.first)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :set_project, only: [:new, :create, :edit]
  def new
  	@card = Card.new
  end

  def create
  	@card = Card.new(card_params)
  	@card.body = "Put your text here..."
  	@card.project = Project.find(params[:project_id])
    if @project.cards.last
        @card.position = @project.cards.last.position + 1
    else
        @card.position = 1
    end  
    

  	if @card.save
  		respond_to do |format|
  			format.html { redirect_to new_project_card_path(@card.project), notice: 
  			"New card created" }
  			format.js 
  		end
  	else 
  		respond_to do |format|
  			format.html { render :new }	
  			format.js 
  		end
  	end
  end

  def edit
  	@card = Card.find(params[:id])
  end

  def update
  	@card = Card.find(params[:id])
  	if @card.update(card_params)
  		respond_to do |format|
  			format.html {redirect_to project_path(@card.project), notice: "Card updated"}
  			format.json { respond_with_bip(@card) }
  		end
  	else
  		respond_to do |format|
  			format.html { render :edit }
  			format.json { respond_with_bip(@card) }	
  		end
  	end
  end

  def destroy
  	@card = Card.find(params[:id])
  	@card.destroy
  	respond_to do |format|
  		format.html { redirect_to project_path(@card.project), notice: "Card deleted"}
  		format.js { head :no_content }
  	end
  end

  def sort
    cards = params[:card]
    cards.each.with_index do |card, index|
      Card.find(card).update(position: (index + 1))
    end
    respond_to do |format|
      format.js { head :no_content }
    end
  end

  private
  def card_params
  	params.require(:card).permit(:project_id, :body, :title, :position)
  end

  def set_project
  	@project = Project.find(params[:project_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: :show
  def index
  	@projects = current_user.projects
  end

  def new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: "Project updated" }
        format.json { respond_with_bip(@project) }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { respond_with_bip(@project) } 
      end
    end
  end

  def show
  	@project = Project.find(params[:id])
  	@cards = @project.cards
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: "Project deleted!"}
      format.js {head :no_content}
    end
  end

  private
  def project_params
    params.require(:project).permit(:user_id, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path, notice: "Welcome aboard!"
  	else
  		render :new
  	end	
  end

  def edit
  end

  def index
  end

  def show
  end

  private
  def user_params
  	params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<%= content_tag_for :div, card do %>
	<div class="header">
		<div class="nav"><%= link_to "X", project_card_path(@project, card), method: :delete, remote: true %></div>
		<%= content_tag :h3,  best_in_place(card, :title, path: project_card_path(@project, card))  %>
	</div>
	<%= content_tag :p, best_in_place(card, :body, path: project_card_path(@project, card)) %>
<% end %>	

app/views/cards/create.js.erb
$("#board").append("<%= j render partial: "card", object: @card %>");

app/views/cards/edit.html.erb
<h1>Edit Card</h1>
<% if :notice %><%= notice %><% end %>
<%= form_for [@project, @card] do |f| %>
	<%= f.text_field :title, placeholder: "title" %>
	<br>
	<%= f.text_area :body, placeholder: "body" %>
	<br>
	<%= f.submit :edit %>
<% end %>

app/views/cards/new.html.erb
<h1>New Card</h1>
<% if :notice %><%= notice %><% end %>
<%= form_for [@project, @card] do |f| %>
	<%= f.text_field :title, placeholder: "title" %>
	<br>
	<%= f.text_area :body, placeholder: "body" %>
	<br>
	<%= f.submit :create %>
<% end %>
   

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/header' %>
	<div class="dismiss"><% if notice %><p  id="notice"><%= notice %> | <div class="dissbutt"><%= link_to "x" %></p><% end %></div></div>
	<div class="dismiss"><% if alert %><p id="alert"><%= alert %> | <div class="dissbutt"><%= link_to "x" %></p><% end %></div></div>
<%= yield %>
</body>
</html>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects</h1>
<% @projects.each do |project| %>
	<%= link_to project.title, project_path(project)%>(<%= link_to "X", project_path(project), method: "delete" %>)
	<br>
	<br>
<% end %>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<div id="board" class="board" data-update-url="<%= sort_project_cards_path @project %>">
	<%= render partial: 'cards/card', collection: @cards %>
</div>

app/views/shared/_header.html.erb
<header>
	<% if user_signed_in? && @project %>
		<nav>
			<%=link_to 'sign out', destroy_user_session_path, method: :delete %> | <%= link_to 'projects', projects_path %>
			<%= link_to "new card", project_cards_path(@project, card: {title: "???"}), method: :post, remote: true, class:"button" %>
		</nav>		
			<%= content_tag :h1, best_in_place(@project, :title)%>
	<% elsif user_signed_in? %>	
		<nav>
			<%=link_to 'sign out', destroy_user_session_path, method: :delete %> | <%= link_to 'projects', projects_path %>
		</nav>		
			<%= content_tag :h1, current_user.name %>
	<% else %>
		<nav>
			<%= link_to 'sign in', new_user_session_path %> | <%= link_to 'sign up', new_user_registration_path %>
		</nav>		
			<%= content_tag :h1, "Cards" %>
	<% end %>		
</header>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>